language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - cat $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini > ./xdebug.ini
  - phpenv config-rm xdebug.ini || true
  - composer self-update

before_script:
  - composer install --prefer-source
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/php-cs-fixer fix --dry-run --diff --level psr2 .
  - phpenv config-add ./xdebug.ini

script:
  - php -dzend_extension=xdebug.so /vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - jamie.hannaford@rackspace.com
    - thanhha.work@gmail.com
